package Sistema;

import data.*;
import java.awt.*;
import javax.swing.*;
import org.jfree.chart.*;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 * @author maxim
 */
public class Graficas extends javax.swing.JFrame {
    private PorcentajesCuentas porcentajesCuentas;
    private boolean lineas = false;
    /**
     * Creates new form GraficasYPorcentajes
     */
    public Graficas() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setIconImage(Login.img.getImage());
        setImageLabel(logo, "src/img/Finanzasimg.png");
        try {
            porcentajesCuentas = EstaticCuentas.getPorcentajeCuentas();
            System.out.println("\nporcentaje maximo: "+(porcentajeMax()-20)+"%");
            showBarChart(ChartPnl);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        tituloTxt = new javax.swing.JLabel();
        empresaTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        regresarBttnPanel = new javax.swing.JPanel();
        regresarBttnLabel = new javax.swing.JLabel();
        ChartPnl = new javax.swing.JPanel();
        graficoBttnPanel = new javax.swing.JPanel();
        graficoBttnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(51, 51, 51));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTxt.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloTxt.setText("Porcentajes y graficas");
        BG.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        empresaTxt.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        empresaTxt.setForeground(new java.awt.Color(255, 255, 255));
        empresaTxt.setText("TEQUILERA LA CARIÑOSA S.A DE C.V");
        BG.add(empresaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        logo.setText("logo");
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        regresarBttnPanel.setBackground(new java.awt.Color(76, 76, 76));
        regresarBttnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarBttnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresarBttnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresarBttnPanelMouseExited(evt);
            }
        });

        regresarBttnLabel.setForeground(new java.awt.Color(255, 255, 255));
        regresarBttnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresarBttnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        regresarBttnLabel.setText("Regresar");
        regresarBttnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout regresarBttnPanelLayout = new javax.swing.GroupLayout(regresarBttnPanel);
        regresarBttnPanel.setLayout(regresarBttnPanelLayout);
        regresarBttnPanelLayout.setHorizontalGroup(
            regresarBttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regresarBttnPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresarBttnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        regresarBttnPanelLayout.setVerticalGroup(
            regresarBttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regresarBttnPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresarBttnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(regresarBttnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 100, 40));

        ChartPnl.setBackground(new java.awt.Color(255, 255, 255));
        ChartPnl.setLayout(new java.awt.BorderLayout());
        BG.add(ChartPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 870, 450));

        graficoBttnPanel.setBackground(new java.awt.Color(76, 76, 76));
        graficoBttnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graficoBttnPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                graficoBttnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                graficoBttnPanelMouseExited(evt);
            }
        });

        graficoBttnLabel.setForeground(new java.awt.Color(255, 255, 255));
        graficoBttnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        graficoBttnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/graficas.png"))); // NOI18N
        graficoBttnLabel.setText("Lineas");
        graficoBttnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout graficoBttnPanelLayout = new javax.swing.GroupLayout(graficoBttnPanel);
        graficoBttnPanel.setLayout(graficoBttnPanelLayout);
        graficoBttnPanelLayout.setHorizontalGroup(
            graficoBttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficoBttnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        graficoBttnPanelLayout.setVerticalGroup(
            graficoBttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficoBttnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BG.add(graficoBttnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBttnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBttnPanelMouseEntered
        regresarBttnPanel.setBackground(new Color(100,100,100));
    }//GEN-LAST:event_regresarBttnPanelMouseEntered

    private void regresarBttnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBttnPanelMouseExited
        regresarBttnPanel.setBackground(new Color(76,76,76));
    }//GEN-LAST:event_regresarBttnPanelMouseExited

    private void regresarBttnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBttnPanelMouseClicked
        this.dispose();
        new Aumentos_Y_Disminuciones().setVisible(true);
    }//GEN-LAST:event_regresarBttnPanelMouseClicked

    private void graficoBttnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficoBttnPanelMouseClicked
        if (!lineas) {
            showLineChart(ChartPnl);
            graficoBttnLabel.setText("Barras");
            lineas = true;
        } else {
            showBarChart(ChartPnl);
            graficoBttnLabel.setText("Lineas");
            lineas = false;
        }
    }//GEN-LAST:event_graficoBttnPanelMouseClicked

    private void graficoBttnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficoBttnPanelMouseEntered
        graficoBttnPanel.setBackground(new Color(100,100,100));
    }//GEN-LAST:event_graficoBttnPanelMouseEntered

    private void graficoBttnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficoBttnPanelMouseExited
        graficoBttnPanel.setBackground(new Color(76,76,76));
    }//GEN-LAST:event_graficoBttnPanelMouseExited

    //Funciones
    public void setImageLabel (JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public void showBarChart(JPanel panelName){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(porcentajesCuentas.getCaja(), "%", "Caja");
        dataset.setValue(porcentajesCuentas.getBanco(), "%", "Bancos");
        dataset.setValue(porcentajesCuentas.getClientes(), "%", "Clientes");
        dataset.setValue(porcentajesCuentas.getInventario(), "%", "Inventario");
        dataset.setValue(porcentajesCuentas.getMobiliario(), "%", "Mobiliario");
        dataset.setValue(porcentajesCuentas.getMaquinaria(), "%", "Maquinaria");
        dataset.setValue(porcentajesCuentas.getTransporte(), "%", "Transporte");
        dataset.setValue(porcentajesCuentas.getTerreno(), "%", "Terreno");
        dataset.setValue(porcentajesCuentas.getEquipoComp(), "%", "Equipo comp.");
        dataset.setValue(porcentajesCuentas.getProveedores(), "%", "Proveedores");
        dataset.setValue(porcentajesCuentas.getCtasPPagar(), "%", "cuentas x pagar");
        dataset.setValue(porcentajesCuentas.getArrendamiento(), "%", "Arrendamiento");
        dataset.setValue(porcentajesCuentas.getCapSocial(), "%", "Capital social");
        dataset.setValue(porcentajesCuentas.getUtilNet(), "%", "Utilidad");
        
        JFreeChart chart = ChartFactory.createBarChart("Porcentajes Aumento y disminucion","Cuentas","%", 
                dataset, PlotOrientation.VERTICAL, false, true, false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        NumberAxis axis = new NumberAxis();
        axis.setRange(porcentajeMax()*(-1), porcentajeMax());
        categoryPlot.setRangeAxis(axis);
        categoryPlot.setRangeGridlinePaint(Color.BLACK);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(72,26,32);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        panelName.removeAll();
        panelName.add(barpChartPanel, BorderLayout.CENTER);
        panelName.validate();
    }
    
    public void showLineChart(JPanel panelName){
        //create dataset for the graph
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(porcentajesCuentas.getCaja(), "%", "Caja");
        dataset.setValue(porcentajesCuentas.getBanco(), "%", "Bancos");
        dataset.setValue(porcentajesCuentas.getClientes(), "%", "Clientes");
        dataset.setValue(porcentajesCuentas.getInventario(), "%", "Inventario");
        dataset.setValue(porcentajesCuentas.getMobiliario(), "%", "Mobiliario");
        dataset.setValue(porcentajesCuentas.getMaquinaria(), "%", "Maquinaria");
        dataset.setValue(porcentajesCuentas.getTransporte(), "%", "Transporte");
        dataset.setValue(porcentajesCuentas.getTerreno(), "%", "Terreno");
        dataset.setValue(porcentajesCuentas.getEquipoComp(), "%", "Equipo comp.");
        dataset.setValue(porcentajesCuentas.getProveedores(), "%", "Proveedores");
        dataset.setValue(porcentajesCuentas.getCtasPPagar(), "%", "cuentas x pagar");
        dataset.setValue(porcentajesCuentas.getArrendamiento(), "%", "Arrendamiento");
        dataset.setValue(porcentajesCuentas.getCapSocial(), "%", "Capital social");
        dataset.setValue(porcentajesCuentas.getUtilNet(), "%", "Utilidad");
        
        //create chart
        JFreeChart linechart = ChartFactory.createLineChart("Porcentajes Aumento y disminucion","Cuentas","%", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        //create plot object
        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
        NumberAxis axis = new NumberAxis();
        axis.setRange(porcentajeMax()*(-1), porcentajeMax());
        lineCategoryPlot.setRangeAxis(axis);
        lineCategoryPlot.setRangeGridlinePaint(Color.BLACK);
        lineCategoryPlot.setBackgroundPaint(Color.white);
        
        //create render object to change the moficy the line properties like color
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(72,26,32);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        
        //create chartPanel to display chart(graph)
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        panelName.removeAll();
        panelName.add(lineChartPanel, BorderLayout.CENTER);
        panelName.validate();
    }
    private double porcentajeMax() {
        double porcentajeMax=0;
        double arr[] = {
            porcentajesCuentas.getCaja(),
            porcentajesCuentas.getBanco(),
            porcentajesCuentas.getClientes(),
            porcentajesCuentas.getInventario(),
            porcentajesCuentas.getMobiliario(),
            porcentajesCuentas.getMaquinaria(),
            porcentajesCuentas.getTransporte(),
            porcentajesCuentas.getTerreno(),
            porcentajesCuentas.getEquipoComp(),
            porcentajesCuentas.getProveedores(),
            porcentajesCuentas.getCtasPPagar(),
            porcentajesCuentas.getArrendamiento(),
            porcentajesCuentas.getCapSocial(),
            porcentajesCuentas.getUtilNet()
        };
        for (int i = 1; i < arr.length; i++)
            if (arr[i] > porcentajeMax)
                porcentajeMax = arr[i];
        return porcentajeMax+20;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel ChartPnl;
    private javax.swing.JLabel empresaTxt;
    private javax.swing.JLabel graficoBttnLabel;
    private javax.swing.JPanel graficoBttnPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel regresarBttnLabel;
    private javax.swing.JPanel regresarBttnPanel;
    private javax.swing.JLabel tituloTxt;
    // End of variables declaration//GEN-END:variables
}
