package Sistema;

import data.LoginStatic;
import java.awt.*;
import javax.swing.*;

/**
 * @author yaren
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public static ImageIcon img = new ImageIcon("src/img/logo_icon.png");
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setIconImage(Login.img.getImage());
        setImageLabel(logo, "src/img/Finanzasimg.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        sloganTxt = new javax.swing.JLabel();
        colaboradoresBttn = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JLabel();
        contraTxt = new javax.swing.JLabel();
        contraPswdField = new javax.swing.JPasswordField();
        usuarioTxtField = new javax.swing.JTextField();
        icon_label = new javax.swing.JLabel();
        loginBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema financiero La cariñosa");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        logoPanel.setBackground(new java.awt.Color(0, 0, 0));

        logo.setText("logo");

        sloganTxt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        sloganTxt.setForeground(new java.awt.Color(255, 255, 255));
        sloganTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sloganTxt.setText("\"Calienta tu corazón con cada trago\"");

        colaboradoresBttn.setBackground(new java.awt.Color(0, 0, 0));
        colaboradoresBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        colaboradoresBttn.setForeground(new java.awt.Color(255, 255, 255));
        colaboradoresBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colaborators.png"))); // NOI18N
        colaboradoresBttn.setText("Colaboradores");
        colaboradoresBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradoresBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logoPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(sloganTxt))
                    .addGroup(logoPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logoPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(colaboradoresBttn)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sloganTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(colaboradoresBttn)
                .addGap(20, 20, 20))
        );

        loginPanel.setBackground(new java.awt.Color(51, 51, 51));

        usuarioTxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        usuarioTxt.setForeground(new java.awt.Color(255, 255, 255));
        usuarioTxt.setText("Usuario:");

        contraTxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        contraTxt.setForeground(new java.awt.Color(255, 255, 255));
        contraTxt.setText("Contraseña:");

        contraPswdField.setBackground(new java.awt.Color(76, 76, 76));
        contraPswdField.setForeground(new java.awt.Color(255, 255, 255));
        contraPswdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraPswdField.setText("............");
        contraPswdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraPswdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraPswdFieldFocusLost(evt);
            }
        });
        contraPswdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraPswdFieldKeyPressed(evt);
            }
        });

        usuarioTxtField.setBackground(new java.awt.Color(76, 76, 76));
        usuarioTxtField.setForeground(new java.awt.Color(255, 255, 255));
        usuarioTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioTxtFieldKeyPressed(evt);
            }
        });

        icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil.png"))); // NOI18N

        loginBttn.setBackground(new java.awt.Color(51, 51, 51));
        loginBttn.setForeground(new java.awt.Color(255, 255, 255));
        loginBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        loginBttn.setText("Entrar");
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(contraPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(usuarioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(contraTxt))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(icon_label))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(loginBttn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(icon_label)
                .addGap(18, 18, 18)
                .addComponent(usuarioTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(loginBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colaboradoresBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradoresBttnActionPerformed
        this.dispose();
        new Colaboradores().setVisible(true);
    }//GEN-LAST:event_colaboradoresBttnActionPerformed

    private void contraPswdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraPswdFieldKeyPressed
        if(evt.getKeyCode()==10){
            checkLogIn(usuarioTxtField, contraPswdField);
        }
    }//GEN-LAST:event_contraPswdFieldKeyPressed

    private void usuarioTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTxtFieldKeyPressed
        if(evt.getKeyCode()==10) {
            contraPswdField.requestFocus();
        }
    }//GEN-LAST:event_usuarioTxtFieldKeyPressed

    private void contraPswdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraPswdFieldFocusGained
        contraPswdField.setText("");
    }//GEN-LAST:event_contraPswdFieldFocusGained

    private void contraPswdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraPswdFieldFocusLost
        if (contraPswdField.getText().isBlank()) {
            contraPswdField.setText("............");
        }
    }//GEN-LAST:event_contraPswdFieldFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        usuarioTxtField.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        checkLogIn(usuarioTxtField, contraPswdField);
    }//GEN-LAST:event_loginBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                //new Menú().setVisible(true); //esto es  para no andar haciendo en login que que perra hueva
                
            }
        });
    }
    
    private void checkLogIn (JTextField usurarioTxtField, JPasswordField contraFieldName) {
        if (usurarioTxtField.getText().matches(LoginStatic.getUsuario()) || usurarioTxtField.getText().matches(LoginStatic.getUsuarioAdm())) {
            if (contraFieldName.getText().matches(LoginStatic.getContra()) || contraFieldName.getText().matches(LoginStatic.getContraAdm())){
                System.out.println("Inicio de sesion exitoso");
                JOptionPane.showMessageDialog(null, "Inicio de sesion exitoso");
                LoginStatic.setLogedin(true);
                
                this.dispose();
                new Menu().setVisible(true);
            } else{
                System.out.println("Contraseña incorrecta");
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        }
        else{
            System.out.println(" USUARIO O CONTRASEÑA NO VALIDOS");
            JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA NO VALIDOS");
        }
    }
    
    public void setImageLabel (JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colaboradoresBttn;
    private javax.swing.JPasswordField contraPswdField;
    private javax.swing.JLabel contraTxt;
    private javax.swing.JLabel icon_label;
    private javax.swing.JButton loginBttn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel sloganTxt;
    private javax.swing.JLabel usuarioTxt;
    private javax.swing.JTextField usuarioTxtField;
    // End of variables declaration//GEN-END:variables
}
