package Sistema;

import Sistema_Manual.ManualDeUsuario;
import java.awt.*;
import javax.swing.*;

/**
 * @author yaren
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menu() {
        initComponents();
        this.setIconImage(Login.img.getImage());
        this.setLocationRelativeTo(this);
        setImageLabel(logo, "src/img/Finanzasimg.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        menuTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        balanceGerenalBttn = new javax.swing.JButton();
        EstadoResulBttn = new javax.swing.JButton();
        razonesFincBttn = new javax.swing.JButton();
        flujoEfectivoBttn = new javax.swing.JButton();
        salirBttn = new javax.swing.JButton();
        colaboradoresBttn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema financiero La cariñosa");
        setBackground(new java.awt.Color(0, 0, 0));

        BG.setBackground(new java.awt.Color(51, 51, 51));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuTxt.setForeground(new java.awt.Color(255, 255, 255));
        menuTxt.setText("Menú");
        BG.add(menuTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 59, -1));

        logo.setText("logo");
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 290));

        balanceGerenalBttn.setBackground(new java.awt.Color(94, 12, 12));
        balanceGerenalBttn.setForeground(new java.awt.Color(255, 255, 255));
        balanceGerenalBttn.setText("BALANCE GENERAL");
        balanceGerenalBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceGerenalBttnActionPerformed(evt);
            }
        });
        BG.add(balanceGerenalBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 68));

        EstadoResulBttn.setBackground(new java.awt.Color(94, 12, 12));
        EstadoResulBttn.setForeground(new java.awt.Color(255, 255, 255));
        EstadoResulBttn.setText("ESTADO DE RESULTADOS");
        EstadoResulBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoResulBttnActionPerformed(evt);
            }
        });
        BG.add(EstadoResulBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 210, 68));

        razonesFincBttn.setBackground(new java.awt.Color(94, 12, 12));
        razonesFincBttn.setForeground(new java.awt.Color(255, 255, 255));
        razonesFincBttn.setText("ANALISIS DE RAZONES FINANCIERAS");
        razonesFincBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        razonesFincBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razonesFincBttnActionPerformed(evt);
            }
        });
        BG.add(razonesFincBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 220, 68));

        flujoEfectivoBttn.setBackground(new java.awt.Color(94, 12, 12));
        flujoEfectivoBttn.setForeground(new java.awt.Color(255, 255, 255));
        flujoEfectivoBttn.setText("FLUJO DE EFECTIVO");
        flujoEfectivoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flujoEfectivoBttnActionPerformed(evt);
            }
        });
        BG.add(flujoEfectivoBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 220, 68));

        salirBttn.setBackground(new java.awt.Color(51, 51, 51));
        salirBttn.setForeground(new java.awt.Color(255, 255, 255));
        salirBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        salirBttn.setText("SALIR");
        salirBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBttnActionPerformed(evt);
            }
        });
        BG.add(salirBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, 30));

        colaboradoresBttn.setBackground(new java.awt.Color(51, 51, 51));
        colaboradoresBttn.setForeground(new java.awt.Color(255, 255, 255));
        colaboradoresBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colaborators.png"))); // NOI18N
        colaboradoresBttn.setText("Colaboradores");
        colaboradoresBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradoresBttnActionPerformed(evt);
            }
        });
        BG.add(colaboradoresBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Document-Blank.png"))); // NOI18N
        jButton1.setText("Manual de usuario");
        jButton1.setHideActionText(true);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EstadoResulBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoResulBttnActionPerformed
        this.dispose();
        new EstadoDeResultados().setVisible(true);
    }//GEN-LAST:event_EstadoResulBttnActionPerformed

    private void balanceGerenalBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceGerenalBttnActionPerformed
        this.dispose();
        new BalanceGeneral().setVisible(true);
    }//GEN-LAST:event_balanceGerenalBttnActionPerformed

    private void salirBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBttnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBttnActionPerformed

    private void razonesFincBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razonesFincBttnActionPerformed
        this.dispose();
        new Razones_financieras().setVisible(true);
    }//GEN-LAST:event_razonesFincBttnActionPerformed

    private void flujoEfectivoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flujoEfectivoBttnActionPerformed
        this.dispose();
        new Fluo_de_efectivo().setVisible(true);
    }//GEN-LAST:event_flujoEfectivoBttnActionPerformed

    private void colaboradoresBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradoresBttnActionPerformed
        this.dispose();
        new Colaboradores().setVisible(true);
    }//GEN-LAST:event_colaboradoresBttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new ManualDeUsuario().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setImageLabel (JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton EstadoResulBttn;
    private javax.swing.JButton balanceGerenalBttn;
    private javax.swing.JButton colaboradoresBttn;
    private javax.swing.JButton flujoEfectivoBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JButton razonesFincBttn;
    private javax.swing.JButton salirBttn;
    // End of variables declaration//GEN-END:variables
}
